version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: drewhyatt
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: drewhyatt
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  api:
    build: ./apps/api
    expose:
      - "4000"
    env_file:
      - ./apps/api/.env
    environment:
      DATABASE_URL: postgresql://drewhyatt:localdev@db:5432/drewhyatt
    depends_on:
      - db
      - mailhog

  www:
    build: ./apps/www
    volumes:
      - www_dist:/srv/www

  games:
    build: ./apps/games/web
    volumes:
      - games_dist:/srv/games

  caddy:
    build: ./infra/caddy
    ports:
      - "80:80"
    depends_on:
      - api
      - www
      - games
    volumes:
      - www_dist:/srv/www
      - games_dist:/srv/games

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
  www_dist:
  games_dist:
