services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: drewhyatt
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: drewhyatt
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    environment:
      DATABASE_URL: postgresql://drewhyatt:localdev@db:5432/drewhyatt
    depends_on:
      - db
      - mailhog

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
